// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:10176072-7591-4022-801a-ceeb91bd1a39",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X5FhuW4gT",
    "aws_user_pools_web_client_id": "3i4l8snet95j6ohetkgb66cu7t"
};


export default awsmobile;
